version: '3'

services:
  site:
    build:
      context: ./config/php/
    container_name: 'toukou-site'
    restart: unless-stopped
    ports:
      - '8888:80'
    links:
      - database
    volumes:
      - ./site:/var/www
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - toukou-network
  nginx:
    build:
      context: ./config/nginx/
    container_name: 'toukou-nginx'
    restart: unless-stopped
    ports:
      - 88:80
      - 443:443
    volumes:
      - ./site:/var/www
      - ./config/nginx/:/etc/nginx/conf.d/
    networks:
      - toukou-network
    depends_on:
      - site
  database:
    image: mysql:5.7
    restart: unless-stopped
    container_name: 'toukou-db'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '127.0.0.1:2222:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    networks:
      - toukou-network

networks:
  toukou-network:
    driver: bridge
